name: Deploy VitePress to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build VitePress
        run: npx vitepress build docs

      - name: Debug - List dist directory
        run: ls -la docs/.vitepress/dist/

      - name: Create .nojekyll
        run: touch docs/.vitepress/dist/.nojekyll

      - name: Copy CNAME
        run: cp docs/.vitepress/CNAME docs/.vitepress/dist/CNAME

      - name: Debug - List dist directory after copying
        run: ls -la docs/.vitepress/dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
          force_orphan: true
          commit_message: "Deploy to GitHub Pages"