name: Deploy VitePress to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Debug - List current directory
        run: pwd && ls -la

      - name: Install dependencies
        run: |
          npm install
          npm list vitepress

      - name: Build VitePress
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing docs directory:"
          ls -la docs
          echo "Listing .vitepress directory:"
          ls -la docs/.vitepress
          npx vitepress build docs --debug

      - name: Debug - List dist directory
        run: |
          echo "Listing dist directory:"
          ls -la docs/.vitepress/dist || echo "dist directory not found"

      - name: Create .nojekyll
        run: |
          mkdir -p docs/.vitepress/dist
          touch docs/.vitepress/dist/.nojekyll

      - name: Copy CNAME
        run: |
          cp docs/.vitepress/CNAME docs/.vitepress/dist/CNAME || echo "CNAME file not found"

      - name: Debug - List dist directory after copying
        run: |
          echo "Listing dist directory after copying:"
          ls -la docs/.vitepress/dist || echo "dist directory not found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
          force_orphan: true
          commit_message: "Deploy to GitHub Pages"
          enable_jekyll: false